name: ZF Matriks Perakitan

on:
  push:
    branches: [ "main", "master" ]

jobs:
  build:
    name: Kompilasi APK
    runs-on: ubuntu-latest

    steps:
    - name: Ekstraksi Repositori
      uses: actions/checkout@v4

    - name: Injeksi JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-version: '8.2'

    - name: Eksekusi Kompilasi
      run: gradle assembleDebug

    - name: Ekstraksi Artefak APK
      uses: actions/upload-artifact@v4
      with:
        name: ZuhriWeather-Widget
        path: app/build/outputs/apk/debug/*.apk
